### ISSUE TITLE
Need new version published to Crates.io

### ISSUE THREAD

**Issue by ELD** [outersky/r2d2-mysql#11]
Looking at the `Cargo.toml`, the repo marks this crate as version `9.0.0`, yet the version that's known to Crates.io is only version `8.0.0`. So any of the latest fixes (including my PR, #10) aren't available via the standard `Cargo.toml` inclusion.

I'd like for you to upload a new version of the crate to Crates.io (`cargo publish`).

Thanks!

**Comment by outersky** [comment]
published now, sorry!
