### ISSUE TITLE
r2d2 mysql 8.0 can not work.

### ISSUE THREAD

**Issue by damody** [outersky/r2d2-mysql#12]
can see this example project.
https://github.com/damody/r2d2mysql

always get time out 
https://github.com/damody/r2d2mysql/blob/81e94cd757eea1c15f0342f7bd75593b32b5a0b9/src/main.rs#L71
and get error
`Commands out of sync; you can\'t run this command now`

**Comment by outersky** [comment]
sorry, please try 9.0.0
